'''
Example for a validator.

When something goes wrong, an exception is generated by
the functions below. The root cause for this exception,
such as timeout or unsuccessful compilation,
is reported to the student.

When no exception occured until the end of validate(),
a positive feedback is sent.
'''


def validate(job):
    job.prepare_student_files(remove_directories=True)

    # Build the input files provided by the student
    # with GCC, and generate an output file 'helloworld'.
    job.run_build(inputs=['helloworld.c'], output='helloworld')

    # Run the compilation result.
    job.run_program('./helloworld')
